[package]
name = "wu-diff"
version = "0.1.0"
authors = ["bokuweb <bokuweb12@gmail.com>"]

[dependencies]
clippy = { version = "*", optional = true }

[dev-dependencies]
criterion = "*"

[[bench]]
name = "benches"
harness = false
